---
- hosts: all
  roles:
    - sbaerlocher.wmi_exporter
  vars:
    wmi_exporter_architecture: amd64
    wmi_exporter_force_package: true
    wmi_exporter_enabled_collectors: ad,cpu,cs,dhcp,dns,logical_disk,net,os,service,system,
